const fs = require('fs');
const path = require('path');
const filePath = path.join(__dirname, '..', 'src', 'data', 'players.json');
const players = JSON.parse(fs.readFileSync(filePath, 'utf8'));

const newPlayers = [
  // ═══════════════════════════════════════
  // TONY BENNETT - THE LEGEND HIMSELF
  // ═══════════════════════════════════════
  { id: "381", name: "Tony Bennett", team: "Summit MS", positions: ["2B"], bats: "R", throws: "R",
    stats: { avg: 0.342, obp: 0.528, slg: 0.445, hr: 2, speed: 50 },
    overall: 85, category: "current", era: "Legends",
    grades: { contact: 80, power: 50, speed: 50, eye: 80, fielding: 80, arm: 60 },
    nickname: "The Monroney MVP",
    funFact: "MVP of the 1998 Monroney Tournament. Went 1-1 with 3 walks and 4 runs in the championship. Made a diving stop up the middle to end the final. Leadoff royalty.",
    specialty: "Contact Hitter" },

  // ═══════════════════════════════════════
  // TOP PROSPECTS
  // ═══════════════════════════════════════
  { id: "382", name: "Jackson Holliday", team: "BAL", positions: ["SS", "2B"], bats: "L", throws: "R",
    stats: { avg: 0.262, obp: 0.348, slg: 0.408, hr: 12, speed: 72 },
    overall: 82, category: "current", era: "Top Prospects",
    grades: { contact: 62, power: 48, speed: 65, eye: 65, fielding: 62, arm: 58 },
    nickname: "J-Holl", funFact: "Number one overall pick with a bloodline of greatness. The next Orioles franchise player.", specialty: null },
  { id: "383", name: "Roki Sasaki", team: "LAD", positions: ["SP"], bats: "R", throws: "R",
    stats: { era: 2.10, whip: 0.88, k9: 12.5, bb9: 1.8 },
    overall: 88, category: "current", era: "Top Prospects",
    grades: { fastball: 80, breaking: 72, control: 62, stamina: 55, changeup: 48 },
    nickname: "The Monster of Reiwa", funFact: "102 mph from Japan with a perfect game at 18. The most hyped international arm in decades.", specialty: "Strikeout King" },
  { id: "384", name: "Junior Caminero", team: "TB", positions: ["3B", "SS"], bats: "R", throws: "R",
    stats: { avg: 0.278, obp: 0.330, slg: 0.480, hr: 18, speed: 55 },
    overall: 81, category: "current", era: "Top Prospects",
    grades: { contact: 62, power: 55, speed: 50, eye: 48, fielding: 52, arm: 58 },
    nickname: "Junior", funFact: "Dominican teenager with lightning hands and raw power. The Rays found another gem.", specialty: null },
  { id: "385", name: "Dylan Crews", team: "WAS", positions: ["CF", "RF"], bats: "R", throws: "R",
    stats: { avg: 0.275, obp: 0.352, slg: 0.448, hr: 16, speed: 68 },
    overall: 80, category: "current", era: "Top Prospects",
    grades: { contact: 60, power: 50, speed: 62, eye: 58, fielding: 58, arm: 55 },
    nickname: "Crews", funFact: "Second overall pick out of LSU. Five-tool potential with a College World Series pedigree.", specialty: null },
  { id: "386", name: "Jasson Dominguez", team: "NYY", positions: ["CF", "LF"], bats: "S", throws: "R",
    stats: { avg: 0.268, obp: 0.338, slg: 0.475, hr: 20, speed: 78 },
    overall: 82, category: "current", era: "Top Prospects",
    grades: { contact: 55, power: 58, speed: 72, eye: 52, fielding: 58, arm: 58 },
    nickname: "The Martian", funFact: "Switch-hitting phenom signed out of the Dominican at 16. They call him The Martian for a reason.", specialty: "Five Tool" },
  { id: "387", name: "Marcelo Mayer", team: "BOS", positions: ["SS"], bats: "L", throws: "R",
    stats: { avg: 0.280, obp: 0.355, slg: 0.435, hr: 14, speed: 58 },
    overall: 80, category: "current", era: "Top Prospects",
    grades: { contact: 62, power: 45, speed: 52, eye: 60, fielding: 62, arm: 60 },
    nickname: "Mayer", funFact: "Silky smooth shortstop with a left-handed stroke made for Fenway. Boston blue chip.", specialty: null },
  { id: "388", name: "Masyn Winn", team: "STL", positions: ["SS"], bats: "R", throws: "R",
    stats: { avg: 0.258, obp: 0.310, slg: 0.395, hr: 12, speed: 75 },
    overall: 79, category: "current", era: "Top Prospects",
    grades: { contact: 55, power: 42, speed: 68, eye: 45, fielding: 65, arm: 68 },
    nickname: "Masyn", funFact: "Converted pitcher with a cannon arm at shortstop. Wheels and a rifle from the hole.", specialty: "Speedster" },
  { id: "389", name: "Colt Keith", team: "DET", positions: ["2B", "3B"], bats: "L", throws: "R",
    stats: { avg: 0.270, obp: 0.335, slg: 0.418, hr: 13, speed: 48 },
    overall: 78, category: "current", era: "Top Prospects",
    grades: { contact: 62, power: 45, speed: 42, eye: 55, fielding: 55, arm: 52 },
    nickname: "Colt", funFact: "Sweet left-handed swing and a knack for finding the barrel. Tigers infield future.", specialty: null },
  { id: "390", name: "Pete Crow-Armstrong", team: "CHC", positions: ["CF"], bats: "L", throws: "L",
    stats: { avg: 0.248, obp: 0.310, slg: 0.388, hr: 10, speed: 85 },
    overall: 79, category: "current", era: "Top Prospects",
    grades: { contact: 52, power: 38, speed: 78, eye: 48, fielding: 78, arm: 58 },
    nickname: "PCA", funFact: "Glides around center field like a Gold Glover already. Born to play defense and run.", specialty: "Defensive Wizard" },
  { id: "391", name: "Evan Carter", team: "TEX", positions: ["LF", "CF"], bats: "L", throws: "L",
    stats: { avg: 0.265, obp: 0.362, slg: 0.418, hr: 12, speed: 72 },
    overall: 80, category: "current", era: "Top Prospects",
    grades: { contact: 58, power: 45, speed: 65, eye: 62, fielding: 55, arm: 48 },
    nickname: "E-Cart", funFact: "Called up at 20 and immediately looked like a veteran. Plays the game the right way.", specialty: null },
  { id: "392", name: "Roman Anthony", team: "BOS", positions: ["LF", "CF"], bats: "L", throws: "R",
    stats: { avg: 0.272, obp: 0.358, slg: 0.468, hr: 18, speed: 65 },
    overall: 81, category: "current", era: "Top Prospects",
    grades: { contact: 58, power: 55, speed: 58, eye: 60, fielding: 55, arm: 55 },
    nickname: "Roman", funFact: "Six-foot-two with a picture-perfect left-handed swing. Future middle of the order bat.", specialty: null },
  { id: "393", name: "Ethan Salas", team: "SD", positions: ["C"], bats: "S", throws: "R",
    stats: { avg: 0.268, obp: 0.342, slg: 0.420, hr: 14, speed: 32 },
    overall: 79, category: "current", era: "Top Prospects",
    grades: { contact: 58, power: 48, speed: 28, eye: 55, fielding: 60, arm: 62 },
    nickname: "Salas", funFact: "Switch-hitting catcher signed at 16. The youngest catching prospect anyone can remember.", specialty: null },
  { id: "394", name: "Chase Burns", team: "CIN", positions: ["SP"], bats: "R", throws: "R",
    stats: { era: 3.25, whip: 1.15, k9: 11.0, bb9: 3.0 },
    overall: 80, category: "current", era: "Top Prospects",
    grades: { fastball: 75, breaking: 62, control: 48, stamina: 55, changeup: 45 },
    nickname: "Burner", funFact: "Triple-digit heat out of Wake Forest. Second overall pick with a flamethrower arm.", specialty: "Strikeout King" },

  // ═══════════════════════════════════════
  // SEMI-STARS & SOLID VETS
  // ═══════════════════════════════════════
  { id: "395", name: "Jim Edmonds", team: "STL", positions: ["CF"], bats: "L", throws: "L",
    stats: { avg: 0.284, obp: 0.376, slg: 0.527, hr: 32, speed: 55 },
    overall: 89, category: "current", era: "2000s Stars",
    grades: { contact: 60, power: 68, speed: 50, eye: 68, fielding: 75, arm: 62 },
    nickname: "Jimmy Ballgame", funFact: "Diving catches and moonshot home runs. The most spectacular center fielder of his era.", specialty: "Defensive Wizard" },
  { id: "396", name: "Bernie Williams", team: "NYY", positions: ["CF"], bats: "S", throws: "R",
    stats: { avg: 0.297, obp: 0.381, slg: 0.477, hr: 24, speed: 58 },
    overall: 89, category: "current", era: "Late 90s Dynasty",
    grades: { contact: 68, power: 55, speed: 52, eye: 68, fielding: 62, arm: 52 },
    nickname: "Bernie", funFact: "Four rings and a guitar. The quiet heartbeat of the Yankee dynasty.", specialty: "Contact Hitter" },
  { id: "397", name: "Fred McGriff", team: "ATL", positions: ["1B"], bats: "L", throws: "L",
    stats: { avg: 0.284, obp: 0.377, slg: 0.509, hr: 34, speed: 32 },
    overall: 88, category: "current", era: "1990s Stars",
    grades: { contact: 62, power: 68, speed: 28, eye: 65, fielding: 55, arm: 48 },
    nickname: "Crime Dog", funFact: "493 home runs of quiet excellence. The Crime Dog finally got his Hall of Fame call.", specialty: "Power Hitter" },
  { id: "398", name: "Larry Walker", team: "COL", positions: ["RF"], bats: "L", throws: "R",
    stats: { avg: 0.313, obp: 0.400, slg: 0.565, hr: 32, speed: 60 },
    overall: 92, category: "current", era: "1990s Stars",
    grades: { contact: 70, power: 68, speed: 55, eye: 68, fielding: 68, arm: 72 },
    nickname: "Boogeyman", funFact: "Canadian five-tool superstar. MVP season at Coors and a rocket arm in right.", specialty: "Five Tool" },
  { id: "399", name: "Tim Salmon", team: "ANA", positions: ["RF", "DH"], bats: "R", throws: "R",
    stats: { avg: 0.282, obp: 0.385, slg: 0.498, hr: 28, speed: 38 },
    overall: 86, category: "current", era: "1990s-2000s",
    grades: { contact: 60, power: 62, speed: 32, eye: 68, fielding: 48, arm: 52 },
    nickname: "King Fish", funFact: "Angel for life. 299 homers and the heart of the 2002 championship run.", specialty: null },
  { id: "400", name: "Carlos Delgado", team: "TOR", positions: ["1B", "DH"], bats: "L", throws: "R",
    stats: { avg: 0.280, obp: 0.383, slg: 0.546, hr: 38, speed: 25 },
    overall: 90, category: "current", era: "2000s Stars",
    grades: { contact: 62, power: 75, speed: 20, eye: 68, fielding: 48, arm: 45 },
    nickname: "Delgado", funFact: "Four home runs in one game. Puerto Rican slugger who terrorized the AL East.", specialty: "Power Hitter" },
  { id: "401", name: "Magglio Ordonez", team: "DET", positions: ["RF"], bats: "R", throws: "R",
    stats: { avg: 0.309, obp: 0.369, slg: 0.502, hr: 26, speed: 42 },
    overall: 87, category: "current", era: "2000s Stars",
    grades: { contact: 72, power: 58, speed: 38, eye: 60, fielding: 50, arm: 55 },
    nickname: "Maggs", funFact: "Walk-off homer to send the Tigers to the World Series. Pure bat-to-ball contact artist.", specialty: "Contact Hitter" },
  { id: "402", name: "Torii Hunter", team: "MIN", positions: ["CF"], bats: "R", throws: "R",
    stats: { avg: 0.277, obp: 0.331, slg: 0.461, hr: 25, speed: 62 },
    overall: 87, category: "current", era: "2000s Stars",
    grades: { contact: 60, power: 58, speed: 55, eye: 50, fielding: 72, arm: 65 },
    nickname: "Spider-Man", funFact: "Robbed home runs like they owed him money. Nine Gold Gloves of pure athleticism.", specialty: "Defensive Wizard" },
  { id: "403", name: "Derrek Lee", team: "CHC", positions: ["1B"], bats: "R", throws: "R",
    stats: { avg: 0.281, obp: 0.365, slg: 0.495, hr: 28, speed: 42 },
    overall: 87, category: "current", era: "2000s Stars",
    grades: { contact: 62, power: 62, speed: 38, eye: 62, fielding: 68, arm: 58 },
    nickname: "D-Lee", funFact: "Hit .335 with 46 homers in 2005. Gold Glove at first with a Wrigley-sized smile.", specialty: null },
  { id: "404", name: "David Wright", team: "NYM", positions: ["3B"], bats: "R", throws: "R",
    stats: { avg: 0.296, obp: 0.376, slg: 0.491, hr: 25, speed: 55 },
    overall: 89, category: "current", era: "2000s Stars",
    grades: { contact: 68, power: 58, speed: 50, eye: 65, fielding: 58, arm: 60 },
    nickname: "Captain America", funFact: "The face of the Mets franchise. Seven All-Star Games and a heart as big as Queens.", specialty: null },
  { id: "405", name: "Troy Tulowitzki", team: "COL", positions: ["SS"], bats: "R", throws: "R",
    stats: { avg: 0.290, obp: 0.361, slg: 0.495, hr: 24, speed: 52 },
    overall: 89, category: "current", era: "2000s Stars",
    grades: { contact: 65, power: 58, speed: 48, eye: 58, fielding: 72, arm: 72 },
    nickname: "Tulo", funFact: "Silky smooth shortstop with serious pop. When healthy, one of the best ever at the position.", specialty: null },
  { id: "406", name: "Jim Thome", team: "CLE", positions: ["1B", "DH"], bats: "L", throws: "R",
    stats: { avg: 0.276, obp: 0.402, slg: 0.554, hr: 40, speed: 25 },
    overall: 92, category: "current", era: "2000s Stars",
    grades: { contact: 58, power: 78, speed: 20, eye: 75, fielding: 42, arm: 42 },
    nickname: "Thome", funFact: "612 home runs. Nicest man in baseball who also happened to hit towering blasts.", specialty: "Power Hitter" },
  { id: "407", name: "Mike Mussina", team: "NYY", positions: ["SP"], bats: "L", throws: "R",
    stats: { era: 3.68, whip: 1.19, k9: 7.1, bb9: 2.0 },
    overall: 89, category: "current", era: "Late 90s-2000s",
    grades: { fastball: 62, breaking: 70, control: 72, stamina: 68, changeup: 62 },
    nickname: "Moose", funFact: "Won his 270th game at age 39. Cerebral pitcher who never got enough credit.", specialty: "Pitching Maestro" },
  { id: "408", name: "Jorge Posada", team: "NYY", positions: ["C"], bats: "S", throws: "R",
    stats: { avg: 0.273, obp: 0.374, slg: 0.474, hr: 24, speed: 28 },
    overall: 88, category: "current", era: "Late 90s Dynasty",
    grades: { contact: 60, power: 58, speed: 22, eye: 68, fielding: 55, arm: 60 },
    nickname: "Georgie", funFact: "Switch-hitting catcher who anchored five championship teams. Core Four forever.", specialty: null },
  { id: "409", name: "Chase Utley", team: "PHI", positions: ["2B"], bats: "L", throws: "R",
    stats: { avg: 0.275, obp: 0.358, slg: 0.465, hr: 22, speed: 58 },
    overall: 89, category: "current", era: "2000s Stars",
    grades: { contact: 62, power: 55, speed: 52, eye: 62, fielding: 65, arm: 58 },
    nickname: "The Man", funFact: "The hardest-nosed player of his generation. Philly loved him like family.", specialty: null },
  { id: "410", name: "Roy Halladay", team: "TOR", positions: ["SP"], bats: "R", throws: "R",
    stats: { era: 3.38, whip: 1.18, k9: 6.9, bb9: 1.9 },
    overall: 92, category: "current", era: "2000s Stars",
    grades: { fastball: 68, breaking: 68, control: 75, stamina: 75, changeup: 62 },
    nickname: "Doc", funFact: "Threw a perfect game and a no-hitter in the playoffs the same year. Workhorse perfection.", specialty: "Pitching Maestro" },
  { id: "411", name: "CC Sabathia", team: "NYY", positions: ["SP"], bats: "L", throws: "L",
    stats: { era: 3.74, whip: 1.26, k9: 7.5, bb9: 2.8 },
    overall: 88, category: "current", era: "2000s Stars",
    grades: { fastball: 68, breaking: 65, control: 62, stamina: 75, changeup: 58 },
    nickname: "CC", funFact: "Carried the Brewers to the playoffs on his back then dominated the Bronx for a decade.", specialty: null },
  { id: "412", name: "Johan Santana", team: "MIN", positions: ["SP"], bats: "L", throws: "L",
    stats: { era: 3.22, whip: 1.13, k9: 9.5, bb9: 2.3 },
    overall: 91, category: "current", era: "2000s Stars",
    grades: { fastball: 68, breaking: 62, control: 68, stamina: 65, changeup: 78 },
    nickname: "Johan", funFact: "Two Cy Youngs and the best changeup anyone had ever seen. Venezuelan excellence.", specialty: "Pitching Maestro" },
  { id: "413", name: "Mark Buehrle", team: "CHW", positions: ["SP"], bats: "L", throws: "L",
    stats: { era: 3.81, whip: 1.28, k9: 5.0, bb9: 2.0 },
    overall: 85, category: "current", era: "2000s Stars",
    grades: { fastball: 48, breaking: 55, control: 72, stamina: 72, changeup: 62 },
    nickname: "Buehrle", funFact: "Perfect game, World Series ring, and pitches thrown in under two hours. Efficiency king.", specialty: "Pitching Maestro" },

  // ═══════════════════════════════════════
  // FAN FAVORITES
  // ═══════════════════════════════════════
  { id: "414", name: "Dustin Pedroia", team: "BOS", positions: ["2B"], bats: "R", throws: "R",
    stats: { avg: 0.299, obp: 0.365, slg: 0.439, hr: 14, speed: 58 },
    overall: 87, category: "current", era: "Fan Favorites",
    grades: { contact: 72, power: 42, speed: 52, eye: 65, fielding: 72, arm: 58 },
    nickname: "Pedey", funFact: "Five-foot-nine wrecking ball. MVP, Rookie of the Year, and the grittiest Red Sox ever.", specialty: "Contact Hitter" },
  { id: "415", name: "Hunter Pence", team: "SF", positions: ["RF"], bats: "R", throws: "R",
    stats: { avg: 0.279, obp: 0.334, slg: 0.461, hr: 22, speed: 58 },
    overall: 84, category: "current", era: "Fan Favorites",
    grades: { contact: 60, power: 55, speed: 52, eye: 50, fielding: 52, arm: 58 },
    nickname: "The Reverend", funFact: "Wild swing, wilder energy. Two championship rings and the greatest pregame speeches ever.", specialty: null },
  { id: "416", name: "Jose Bautista", team: "TOR", positions: ["RF", "DH"], bats: "R", throws: "R",
    stats: { avg: 0.253, obp: 0.362, slg: 0.512, hr: 36, speed: 35 },
    overall: 87, category: "current", era: "Fan Favorites",
    grades: { contact: 50, power: 72, speed: 30, eye: 68, fielding: 45, arm: 52 },
    nickname: "Joey Bats", funFact: "The bat flip heard around the world. From journeyman to 54-homer superstar in one summer.", specialty: "Power Hitter" },
  { id: "417", name: "David Ross", team: "CHC", positions: ["C"], bats: "R", throws: "R",
    stats: { avg: 0.229, obp: 0.310, slg: 0.400, hr: 12, speed: 20 },
    overall: 75, category: "current", era: "Fan Favorites",
    grades: { contact: 48, power: 42, speed: 15, eye: 48, fielding: 62, arm: 58 },
    nickname: "Grandpa Rossy", funFact: "Homered in his final game to help break the 108-year curse. Ultimate teammate.", specialty: "Clutch Performer" },
  { id: "418", name: "Tim Wakefield", team: "BOS", positions: ["SP"], bats: "R", throws: "R",
    stats: { era: 4.41, whip: 1.36, k9: 5.5, bb9: 3.3 },
    overall: 80, category: "current", era: "Fan Favorites",
    grades: { fastball: 25, breaking: 72, control: 55, stamina: 72, changeup: 35 },
    nickname: "Wake", funFact: "The knuckleball danced and so did Boston. 200 wins with the most unpredictable pitch in the game.", specialty: null },
  { id: "419", name: "Fernando Valenzuela", team: "LAD", positions: ["SP"], bats: "L", throws: "L",
    stats: { era: 3.54, whip: 1.24, k9: 6.4, bb9: 3.2 },
    overall: 86, category: "current", era: "Fan Favorites",
    grades: { fastball: 58, breaking: 72, control: 58, stamina: 68, changeup: 55 },
    nickname: "El Toro", funFact: "Fernandomania swept Los Angeles in 1981. A round lefty who looked to the sky and dealt magic.", specialty: null },
  { id: "420", name: "Munenori Kawasaki", team: "TOR", positions: ["SS", "2B"], bats: "L", throws: "R",
    stats: { avg: 0.232, obp: 0.290, slg: 0.275, hr: 1, speed: 55 },
    overall: 64, category: "current", era: "Fan Favorites",
    grades: { contact: 48, power: 15, speed: 50, eye: 38, fielding: 55, arm: 48 },
    nickname: "Muni", funFact: "Bush party! The most beloved utility man in Blue Jays history. Pure joy on a baseball field.", specialty: null },
  { id: "421", name: "Pablo Sandoval", team: "SF", positions: ["3B", "1B"], bats: "S", throws: "R",
    stats: { avg: 0.280, obp: 0.322, slg: 0.448, hr: 18, speed: 28 },
    overall: 82, category: "current", era: "Fan Favorites",
    grades: { contact: 65, power: 52, speed: 22, eye: 42, fielding: 48, arm: 52 },
    nickname: "Kung Fu Panda", funFact: "Three homers in a World Series game. The Panda hit everything no matter where it was thrown.", specialty: "Clutch Performer" },
  { id: "422", name: "Shane Victorino", team: "PHI", positions: ["CF", "RF"], bats: "S", throws: "R",
    stats: { avg: 0.275, obp: 0.340, slg: 0.425, hr: 14, speed: 78 },
    overall: 83, category: "current", era: "Fan Favorites",
    grades: { contact: 60, power: 42, speed: 72, eye: 52, fielding: 62, arm: 55 },
    nickname: "Flyin Hawaiian", funFact: "Grand slam cleared the Monster and the 2013 ALCS. Pure energy from Maui.", specialty: "Speedster" },
  { id: "423", name: "Willians Astudillo", team: "MIN", positions: ["C", "3B"], bats: "R", throws: "R",
    stats: { avg: 0.268, obp: 0.288, slg: 0.388, hr: 6, speed: 15 },
    overall: 66, category: "current", era: "Fan Favorites",
    grades: { contact: 65, power: 32, speed: 10, eye: 22, fielding: 35, arm: 42 },
    nickname: "La Tortuga", funFact: "The Turtle swings at everything and hits most of it. Also pitches. Also plays every position.", specialty: null },
  { id: "424", name: "Nick Swisher", team: "NYY", positions: ["RF", "1B"], bats: "S", throws: "L",
    stats: { avg: 0.249, obp: 0.352, slg: 0.445, hr: 24, speed: 38 },
    overall: 82, category: "current", era: "Fan Favorites",
    grades: { contact: 50, power: 58, speed: 32, eye: 62, fielding: 48, arm: 48 },
    nickname: "Swish", funFact: "Fist pumps and hugs for everyone. The most enthusiastic player in any clubhouse.", specialty: null },
  { id: "425", name: "Nyjer Morgan", team: "MIL", positions: ["CF", "PR"], bats: "L", throws: "L",
    stats: { avg: 0.276, obp: 0.328, slg: 0.352, hr: 3, speed: 88 },
    overall: 72, category: "current", era: "Fan Favorites",
    grades: { contact: 58, power: 22, speed: 80, eye: 45, fielding: 55, arm: 42 },
    nickname: "Tony Plush", funFact: "Walk-off hit to clinch the division. Tony Plush showed up when Milwaukee needed him most.", specialty: "Speedster" },
  { id: "426", name: "Johnny Damon", team: "BOS", positions: ["CF", "LF"], bats: "L", throws: "L",
    stats: { avg: 0.284, obp: 0.352, slg: 0.433, hr: 16, speed: 78 },
    overall: 85, category: "current", era: "Fan Favorites",
    grades: { contact: 65, power: 42, speed: 72, eye: 58, fielding: 52, arm: 35 },
    nickname: "Caveman", funFact: "Grand slam in Game 7 of the 2004 ALCS. The caveman who broke the curse.", specialty: "Speedster" },

  // ═══════════════════════════════════════
  // ONE-CLUB LEGENDS
  // ═══════════════════════════════════════
  { id: "427", name: "Yadier Molina", team: "STL", positions: ["C"], bats: "R", throws: "R",
    stats: { avg: 0.277, obp: 0.327, slg: 0.394, hr: 12, speed: 25 },
    overall: 88, category: "current", era: "One-Club Legends",
    grades: { contact: 62, power: 40, speed: 20, eye: 52, fielding: 78, arm: 80 },
    nickname: "Yadi", funFact: "Two decades in one city. Nine Gold Gloves and nobody dared run on his arm.", specialty: "Defensive Wizard" },
  { id: "428", name: "Adrian Beltre", team: "TEX", positions: ["3B"], bats: "R", throws: "R",
    stats: { avg: 0.286, obp: 0.339, slg: 0.480, hr: 28, speed: 38 },
    overall: 91, category: "current", era: "One-Club Legends",
    grades: { contact: 68, power: 62, speed: 32, eye: 52, fielding: 72, arm: 68 },
    nickname: "Beltre", funFact: "3,166 hits and please do not touch his head. The funniest Hall of Famer who ever played.", specialty: "Contact Hitter" },
  { id: "429", name: "Jeff Kent", team: "SF", positions: ["2B"], bats: "R", throws: "R",
    stats: { avg: 0.290, obp: 0.356, slg: 0.500, hr: 29, speed: 32 },
    overall: 88, category: "current", era: "One-Club Legends",
    grades: { contact: 65, power: 62, speed: 28, eye: 58, fielding: 52, arm: 50 },
    nickname: "Kentaur", funFact: "Most home runs ever by a second baseman. Tough, quiet, and absolutely raked.", specialty: "Power Hitter" },
  { id: "430", name: "Tim Hudson", team: "ATL", positions: ["SP"], bats: "R", throws: "R",
    stats: { era: 3.49, whip: 1.24, k9: 6.0, bb9: 2.5 },
    overall: 86, category: "current", era: "One-Club Legends",
    grades: { fastball: 60, breaking: 62, control: 65, stamina: 68, changeup: 58 },
    nickname: "Huddy", funFact: "222 wins with a devastating sinker. Finally got his ring in his hometown of Atlanta.", specialty: null },
  { id: "431", name: "Curtis Granderson", team: "NYY", positions: ["CF", "RF"], bats: "L", throws: "R",
    stats: { avg: 0.249, obp: 0.335, slg: 0.467, hr: 28, speed: 62 },
    overall: 84, category: "current", era: "Fan Favorites",
    grades: { contact: 48, power: 62, speed: 55, eye: 55, fielding: 55, arm: 52 },
    nickname: "Grandy", funFact: "44 home runs for the Yankees and a Roberto Clemente Award. Great player, even better person.", specialty: null },
  { id: "432", name: "Gary Carter", team: "NYM", positions: ["C"], bats: "R", throws: "R",
    stats: { avg: 0.262, obp: 0.335, slg: 0.439, hr: 24, speed: 35 },
    overall: 90, category: "current", era: "1980s Legend",
    grades: { contact: 58, power: 58, speed: 30, eye: 55, fielding: 72, arm: 68 },
    nickname: "The Kid", funFact: "Expos legend who led the 1986 Miracle Mets. The most enthusiastic catcher who ever lived.", specialty: "Clutch Performer" },

  // ═══════════════════════════════════════
  // FAMOUS MOMENTS
  // ═══════════════════════════════════════
  { id: "433", name: "Bobby Thomson", team: "NYG", positions: ["LF", "3B"], bats: "R", throws: "R",
    stats: { avg: 0.270, obp: 0.332, slg: 0.462, hr: 24, speed: 45 },
    overall: 83, category: "current", era: "Famous Moments",
    grades: { contact: 58, power: 55, speed: 40, eye: 50, fielding: 48, arm: 50 },
    nickname: "The Flying Scot", funFact: "The Shot Heard Round the World. One swing in 1951 that still echoes through baseball history.", specialty: "Clutch Performer" },
  { id: "434", name: "Don Larsen", team: "NYY", positions: ["SP"], bats: "R", throws: "R",
    stats: { era: 3.78, whip: 1.35, k9: 5.5, bb9: 3.2 },
    overall: 78, category: "current", era: "Famous Moments",
    grades: { fastball: 58, breaking: 55, control: 52, stamina: 62, changeup: 48 },
    nickname: "Larsen", funFact: "Perfect game in the World Series. 27 up, 27 down. Never done before or since in October.", specialty: "Clutch Performer" },
  { id: "435", name: "Robin Ventura", team: "NYM", positions: ["3B"], bats: "L", throws: "R",
    stats: { avg: 0.267, obp: 0.356, slg: 0.444, hr: 22, speed: 35 },
    overall: 84, category: "current", era: "Famous Moments",
    grades: { contact: 60, power: 55, speed: 30, eye: 62, fielding: 65, arm: 60 },
    nickname: "Robin", funFact: "Grand Slam Single in the 1999 NLCS. Mobbed at first base before he could touch second.", specialty: "Clutch Performer" },
  { id: "436", name: "Chris Chambliss", team: "NYY", positions: ["1B"], bats: "L", throws: "L",
    stats: { avg: 0.279, obp: 0.331, slg: 0.415, hr: 17, speed: 35 },
    overall: 80, category: "current", era: "Famous Moments",
    grades: { contact: 62, power: 48, speed: 30, eye: 52, fielding: 55, arm: 48 },
    nickname: "Chambliss", funFact: "Walk-off homer to win the 1976 ALCS. Had to fight through fans just to touch home plate.", specialty: "Clutch Performer" },
  { id: "437", name: "Craig Counsell", team: "ARI", positions: ["2B", "SS"], bats: "L", throws: "R",
    stats: { avg: 0.255, obp: 0.342, slg: 0.344, hr: 6, speed: 52 },
    overall: 74, category: "current", era: "Famous Moments",
    grades: { contact: 55, power: 28, speed: 48, eye: 58, fielding: 58, arm: 50 },
    nickname: "Counsell", funFact: "Scored the winning run in the 1997 and 2001 World Series. The weirdest batting stance that worked.", specialty: "Clutch Performer" },
  { id: "438", name: "Dave Roberts", team: "BOS", positions: ["LF", "PR"], bats: "L", throws: "L",
    stats: { avg: 0.266, obp: 0.337, slg: 0.365, hr: 5, speed: 88 },
    overall: 76, category: "current", era: "Famous Moments",
    grades: { contact: 55, power: 28, speed: 80, eye: 52, fielding: 52, arm: 42 },
    nickname: "The Steal", funFact: "One stolen base changed everything. The most important steal in baseball history broke an 86-year curse.", specialty: "Speedster" },
  { id: "439", name: "Harvey Haddix", team: "PIT", positions: ["SP"], bats: "L", throws: "L",
    stats: { era: 3.63, whip: 1.24, k9: 5.8, bb9: 2.5 },
    overall: 78, category: "current", era: "Famous Moments",
    grades: { fastball: 55, breaking: 60, control: 62, stamina: 65, changeup: 52 },
    nickname: "The Kitten", funFact: "Threw 12 perfect innings and still lost the game. The greatest pitching performance that ended in heartbreak.", specialty: null },
  { id: "440", name: "Francisco Cabrera", team: "ATL", positions: ["C", "1B"], bats: "R", throws: "R",
    stats: { avg: 0.247, obp: 0.290, slg: 0.395, hr: 8, speed: 22 },
    overall: 68, category: "current", era: "Famous Moments",
    grades: { contact: 48, power: 42, speed: 18, eye: 35, fielding: 38, arm: 42 },
    nickname: "Cabrera", funFact: "Two-out pinch-hit single to win the 1992 NLCS. Sid slid and baseball history was made.", specialty: "Clutch Performer" },

  // ═══════════════════════════════════════
  // MORE SEMI-STARS / SOLID VETS
  // ═══════════════════════════════════════
  { id: "441", name: "Justin Morneau", team: "MIN", positions: ["1B"], bats: "L", throws: "R",
    stats: { avg: 0.281, obp: 0.345, slg: 0.481, hr: 24, speed: 30 },
    overall: 84, category: "current", era: "2000s Stars",
    grades: { contact: 62, power: 58, speed: 25, eye: 55, fielding: 52, arm: 48 },
    nickname: "The Canadian Crusher", funFact: "Canadian MVP who mashed in Minnesota. Quiet power from the Great White North.", specialty: "Power Hitter" },
  { id: "442", name: "Adrian Gonzalez", team: "LAD", positions: ["1B"], bats: "L", throws: "L",
    stats: { avg: 0.288, obp: 0.358, slg: 0.480, hr: 27, speed: 28 },
    overall: 87, category: "current", era: "2010s Stars",
    grades: { contact: 68, power: 60, speed: 22, eye: 60, fielding: 62, arm: 52 },
    nickname: "A-Gon", funFact: "Mexican-American slugger with a beautiful inside-out swing. Five-time All-Star at first.", specialty: "Contact Hitter" },
  { id: "443", name: "Ben Zobrist", team: "CHC", positions: ["2B", "RF"], bats: "S", throws: "R",
    stats: { avg: 0.264, obp: 0.354, slg: 0.420, hr: 16, speed: 52 },
    overall: 84, category: "current", era: "Fan Favorites",
    grades: { contact: 58, power: 45, speed: 48, eye: 62, fielding: 60, arm: 55 },
    nickname: "Zorilla", funFact: "World Series MVP who broke the longest drought in sports. The ultimate Swiss Army knife.", specialty: "Clutch Performer" },
];

players.push(...newPlayers);
fs.writeFileSync(filePath, JSON.stringify(players, null, 2) + '\n');
console.log(`players.json: ${players.length} (added ${newPlayers.length})`);
